### ISSUE TITLE
Update to Angular 20

### ISSUE THREAD

**Issue by evilaliv3** [flowjs/ngx-flow#127]
Shall we perform any update in relation to angular 20 @Quentigus ?

Thank you if you could perform a small check in order to plan for this update.

Thank you!

**Comment by Quentigus** [comment]
I take it

**Comment by Quentigus** [comment]
We can switch to vitest for unit testing :
https://blog.ninja-squad.com/2025/05/28/what-is-new-angular-20.0/#:~:text=Testing%20with%20Vitest%20%F0%9F%9A%80

I don't know how this library is built and published, I don't know if it can have an impact.

**Comment by Quentigus** [comment]
We can use Angular signals, do you have an opinion?

This could bring about changes in behavior and/or code adaptation needs for the users...

**Comment by evilaliv3** [comment]
Thank you Quentigus, at the moment i dont have an opinion.

I suggest for the moment we should just verify if it works and if we should emit a new release with some fixes.

Did you manage to do some verification already? do current tests pass ?

**Comment by evilaliv3** [comment]
Thank you @Quentigus 

considering that you are the only one active on this maintainance, i would probably suggest for the moment to be chirurgical and eventually just fix what would result not working guaranteing retrocompatibility.

Of course if you are confident to be able to implement the standalone, go for it, but probably better to stage it and implement proper retesting on the matter.

**Comment by Quentigus** [comment]
I just pushed the `angular-20` branch :
 
- [x] ng update
- [x] ESLint support + configuration
- [x] fix on node server
- [x] karma (chrome headless + spec reporter)
- [x] standalone support
- [x] Tests (Unit Tests + Manuel Tests with `ng serve`)
- [ ] Test with real application

**Comment by evilaliv3** [comment]
Cool @Quentigus !

Do you know how is more indicated for a review? 

In previous releases did you include tests with a real application or the currenct status already includes same level of testing of the past?

**Comment by evilaliv3** [comment]
I'm sorry @Quentigus , i'm going longer and i've still not tested.

If you are confident all should be correct and up to date, give me a sign and i will proceed releasing.

\cc @AidasK

**Comment by evilaliv3** [comment]
It seems related to this: https://github.com/ng-packagr/ng-packagr/issues/3089

**Comment by evilaliv3** [comment]
Ok my fault, i saw that you deprecated FlowDirective.

I will be retesting all withing globaleaks and then publishing it again correctly if all works out

**Comment by CosmoFruit** [comment]
@Quentigus  @evilaliv3  
according readme 
`@ViewChild('flow')
  flow: FlowDirective;`

so rename FlowDirective to  FlowConfig looks as bad design. can you explain this desicion? also need update documentation and examples in Readme

**Comment by Quentigus** [comment]
This is done to follow the new Angular styleguide and simplify imports when used in standalone mode.
