### ISSUE TITLE
this.flowConstructor is not a constructor

### ISSUE THREAD

**Issue by pavankumarkatakam** [flowjs/ngx-flow#15]
It is working on development (`./node_modules/.bin/ng serve`) but when I done production build (`./node_modules/.bin/ng build --prod`) then the error is coming as follows
![flowjs_prod](https://user-images.githubusercontent.com/6078669/52954532-7a434380-33b0-11e9-8fe6-c227fb3b2740.png)

 My package json file part

```
    "dependencies": {
        "@angular/animations": "^6.1.10",
        "@angular/cdk": "^6.4.7",
        "@angular/common": "^6.1.10",
        "@angular/compiler": "^6.1.10",
        "@angular/core": "^6.1.10",
        "@angular/forms": "^6.1.10",
        "@angular/http": "^6.1.10",
        "@angular/platform-browser": "^6.1.10",
        "@angular/platform-browser-dynamic": "^6.1.10",
        "@angular/router": "^6.1.10",
        "@flowjs/flow.js": "^2.13.1",
        "@flowjs/ngx-flow": "^0.3.4",
        "@ngui/auto-complete": "^1.0.2",
        "angular2-image-upload": "^1.0.0-rc.2",
        "bootstrap": "^4.2.1",
        "core-js": "^2.6.3",
        "d3": "^3.5.17",
        "file-saver": "^1.3.8",
        "firebase": "^5.8.1",
        "fullcalendar": "^3.10.0",
        "laravel-echo": "^1.5.2",
        "moment": "^2.24.0",
        "ng-fullcalendar": "^1.7.1",
        "ng-pick-datetime": "^6.0.16",
        "ng-pick-datetime-moment": "1.0.7",
        "ng2-file-upload": "^1.3.0",
        "ng2-validation": "^4.2.0",
        "ngx-clipboard": "^8.1.4",
        "ngx-modialog": "^5.0.1",
        "perfect-scrollbar": "^1.1.0",
        "primeicons": "^1.0.0",
        "primeng": "^7.0.5",
        "rxjs": "^6.3.3",
        "rxjs-compat": "^6.3.3",
        "zone.js": "^0.8.29"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.6.8",
        "@angular/cli": "~6.0.8",
        "@angular/compiler-cli": "^6.1.10",
        "@angular/language-service": "^6.1.10",
        "@types/d3": "^3.0.0",
        "@types/file-saver": "^1.3.1",
        "@types/jasmine": "^2.8.16",
        "@types/jasminewd2": "^2.0.6",
        "@types/jquery": "^3.3.29",
        "@types/node": "~8.9.4",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "^2.0.4",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.3.0",
        "shipit-cli": "^3.0.0",
        "shipit-deploy": "^2.4.0",
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "~2.8.0"
    }
```

please help me on this issue.

**Comment by pavankumarkatakam** [comment]
i update all angular dependencies to 7+ but still im getting the error.

**Comment by pavankumarkatakam** [comment]
is anybody there

**Comment by pavankumarkatakam** [comment]
Actaully this problem is stated in Readme file, under SSR problem but im not using ssr just `ng build --prod`.

**Comment by pavankumarkatakam** [comment]
Anyway it is working now

**Comment by aymen7** [comment]
hi @pavankumarkatakam can you please tell me how did you solved this problem cuz I am facing the same issue right now 
thank you

**Comment by pavankumarkatakam** [comment]
You need to inject the token as Flow object in every module. Please check readme last section https://github.com/flowjs/ngx-flow#running-with-server-side-rendering-angular-universal

**Comment by MartinNuc** [comment]
Sorry I dont receive a notification about new issues :-( I have to set it up somewhere.

When exactly does this happen? Can you provide stackblitz with the issue?

**Comment by hioymaci** [comment]
> You need to inject the token as Flow object in every module. Please check readme last section https://github.com/flowjs/ngx-flow#running-with-server-side-rendering-angular-universal

Thank you so much. I added [that provider](https://github.com/flowjs/ngx-flow#running-with-server-side-rendering-angular-universal) to only AppModule then it works.

**Comment by MartinNuc** [comment]
I was able to reproduce the issue however I am not sure why this happens. I updated readme https://github.com/flowjs/ngx-flow#install

So please provide flow.js using injection token:

```typescript
import { NgxFlowModule, FlowInjectionToken } from '@flowjs/ngx-flow';
import Flow from '@flowjs/flow.js';

@NgModule({
  imports: [NgxFlowModule],
  providers: [
    {
      provide: FlowInjectionToken,
      useValue: Flow
    }
  ]
})
export class AppModule
```

If you have any idea why [doing it in the library](https://github.com/flowjs/ngx-flow/blob/master/projects/ngx-flow/src/lib/ngx-flow.module.ts#L12) doesn't work in AOT, please let me know. We can discuss and come with better solution. Thanks! 👍

**Comment by jalchr** [comment]
Hello @MartinNuc 
I've followed your instructions, and updated to v0.3.5 but still getting this error when built for production with AOT.
Any tips for overcoming this error ?

**Comment by MartinNuc** [comment]
@jalchr weird. I've just tried it again and worked for me.

Do you use lazy loaded modules?

Do you provide `FlowInjectionToken` in the root module?

For future release I change the code so `flow.js` is passed not through providers but through factory method (`forRoot`).

**Comment by jalchr** [comment]
> Do you use lazy loaded modules?
Yes, I use lazy loaded modules.

> Do you provide FlowInjectionToken in the root module?
No, I'm providing it in each (currently 2) lazy-loaded module separately.

> For future release I change the code so flow.js is passed not through providers but through factory method (forRoot).
That would minimize ambiguity

**Comment by jalchr** [comment]
Is there a workaround ?

**Comment by jalchr** [comment]
mmm 
I think I found the source of the problem.

![Flow_Wrong](https://user-images.githubusercontent.com/295421/55145035-a8a00580-514a-11e9-9380-a336416ad824.jpeg)

![Flow_correct](https://user-images.githubusercontent.com/295421/55145071-b9507b80-514a-11e9-8afb-f970e63538ab.jpeg)

**Comment by MartinNuc** [comment]
`import Flow from '@flowjs/flow.js' ` should be definitely the correct one. Notice it's also in readme.

Can anyone confirm its the same issue?

**Comment by greatsayan** [comment]
Hi,

I've followed your instructions, update packages, change the import also but still not working for me obviously...

I'm building my application using Webpack (without cli) maybe it's related...?

Any ideas?

Thanks

**Comment by mykola-novytskyi** [comment]
When I used: 
import Flow from '@flowjs/flow.js' 
or 
import {Flow}  from '@flowjs/flow.js' 
I have the next error: 
 Could not find a declaration file for module '@flowjs/flow.js'
'node_modules/@flowjs/flow.js/src/flow.js' implicitly has a
n 'any' type.
  Try `npm install @types/flowjs__flow.js` if it exists or add a new declaration (.d.ts) file containing `declare module '@flowjs/flow.js';`

When I used import with IDE i get 
import { Flow } from '@flowjs/ngx-flow/lib/flow/flow';
I get the next error:
error TS2693: 'Flow' only refers to a type, but is being used as a value here.

**Comment by MartinNuc** [comment]
I updated type definitions for flowjs in definitely typed. Also I am going to release a new version which uses these and also supports Angular 8 so feel free to try it out.

**Comment by mykola-novytskyi** [comment]
Thanks, I have an error because of 
"noImplicitAny": true,

in global tsconfig.json.
As temporary decision - i removed this property.

**Comment by MartinNuc** [comment]
@mykola-novytskyi please try the new version. I changed something which could be related to your issue as well. Thanks.

**Comment by greatsayan** [comment]
Thanks a lot!

I will try the new version soon!

**Comment by mykola-novytskyi** [comment]
The issue is still here.
I have 
    "@flowjs/flow.js": "^2.13.2",
    "@flowjs/ngx-flow": "^0.4.1",

And I added "noImplicitAny": true   to my tsconfig.json 
I have the next error: 
Could not find a declaration file for module '@flowjs/flow.js'. 'NgApp/node_modules/@flowjs/flow.js/src/flow.js' implicitly has an 'any'
 type.
  Try `npm install @types/flowjs__flow.js` if it exists or add a new declaration (.d.ts) file containing `declare module '@flowjs/flow.js';`

**Comment by MartinNuc** [comment]
@mykola-novytskyi can you please create a new issue for this one? It doesn't seem to be related to the  ```this.flowConstructor is not a constructor```

I will take a look into it in next weeks.

**Comment by greatsayan** [comment]
Still have the issue too with the latest version. I'm using angular 8
Can you provide an example with Angular 8 please? The stackblitz you provide is using Angular 6.
Thanks.

**Comment by MartinNuc** [comment]
@greatsayan there is no change with Angular 6->8. If you still have problem with this issue check whether you import `flowjs` correctly. If you put `debugger` to your module file you should be able to do something like `new Flow()` - when this doesn't work you import flowjs in a wrong way.

I created empty project just to try it out with the latest angular-cli and it seems to work fine: https://github.com/MartinNuc/ngx-flow-test

**Comment by osmanraifgunes** [comment]
This solved my problem : https://stackoverflow.com/questions/36795819/when-should-i-use-curly-braces-for-es6-import
